In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
f = '../../ENIGH/data/raw/catun_municipio/AGEEML_20258131423976_utf.csv'
ubica_geo = pd.read_csv(f, encoding="utf-8"
                       # usecols = ['folioviv','aire_acond','entidad','factor']
                      )
ubica_geo.head()

,MAPA,CVE_ENT,NOM_ENT,NOM_ABR,CVE_MUN,NOM_MUN,CVE_CAB,NOM_CAB,POB_TOTAL,POB_MASCULINA,POB_FEMENINA,TOTAL DE VIVIENDAS HABITADAS
0,1001,1,Aguascalientes,Ags.,1,Aguascalientes,0001,Aguascalientes,948990,462073,486917,266942
1,1002,1,Aguascalientes,Ags.,2,Asientos,0001,Asientos,51536,25261,26275,12544
2,1003,1,Aguascalientes,Ags.,3,Calvillo,0001,Calvillo,58250,28563,29687,15556
3,1004,1,Aguascalientes,Ags.,4,Cosío,0001,Cosío,17000,8292,8708,3938
4,1005,1,Aguascalientes,Ags.,5,Jesús María,0001,Jesús María,129929,64219,65710,33229

In [3]:
nombre_edo = "Campeche"
ubica_edo = ubica_geo[ubica_geo["NOM_ENT"].str.contains(nombre_edo, case=False, na=False)]
codigo_edo = ubica_edo['CVE_ENT'].mean()

In [4]:
nombre_mun = "San Francisco de Campeche"
ubica_mun = ubica_geo[ubica_geo["NOM_CAB"].str.contains(nombre_mun, case=False, na=False)]
codigo_mun = ubica_mun['CVE_MUN'].mean()

In [5]:
ubica_mun

,MAPA,CVE_ENT,NOM_ENT,NOM_ABR,CVE_MUN,NOM_MUN,CVE_CAB,NOM_CAB,POB_TOTAL,POB_MASCULINA,POB_FEMENINA,TOTAL DE VIVIENDAS HABITADAS
24,4002,4,Campeche,Camp.,2,Campeche,0001,San Francisco de Campeche,294077,141555,152522,85353

In [6]:
codigo_mun

np.float64(2.0)

In [7]:
codigo_edo

np.float64(4.0)

In [8]:
import pandas as pd

f_viv = '../data/Viviendas00.CSV'
f_per = '../data/Personas00.CSV'

# Variables de filtrado
# codigo_mun = ...
# codigo_edo = ...

# Leer por partes y filtrar
vivienda = pd.concat(
    (chunk[(chunk['MUN'] == codigo_mun) & (chunk['ENT'] == codigo_edo)]
     for chunk in pd.read_csv(f_viv, chunksize=100000)),
    ignore_index=True
)

poblacion = pd.concat(
    (chunk[(chunk['MUN'] == codigo_mun) & (chunk['ENT'] == codigo_edo)]
     for chunk in pd.read_csv(f_per, chunksize=100000)),
    ignore_index=True
)

In [9]:
vivienda.columns

Index(['ENT', 'MUN', 'LOC50K', 'ID_VIV', 'COBERTURA', 'ESTRATO', 'UPM',
       'FACTOR', 'CLAVIVP', 'PAREDES', 'TECHOS', 'PISOS', 'COCINA', 'CUADORM',
       'TOTCUART', 'LUG_COC', 'COMBUSTIBLE', 'ESTUFA', 'ELECTRICIDAD', 'FOCOS',
       'FOCOS_AHORRA', 'AGUA_ENTUBADA', 'ABA_AGUA_ENTU', 'ABA_AGUA_NO_ENTU',
       'TINACO', 'CISTERNA', 'BOMBA_AGUA', 'REGADERA', 'BOILER',
       'CALENTADOR_SOLAR', 'AIRE_ACON', 'PANEL_SOLAR', 'SERSAN', 'CONAGUA',
       'USOEXC', 'DRENAJE', 'SEPARACION1', 'SEPARACION2', 'SEPARACION3',
       'SEPARACION4', 'DESTINO_BAS', 'REFRIGERADOR', 'LAVADORA', 'HORNO',
       'AUTOPROP', 'MOTOCICLETA', 'BICICLETA', 'RADIO', 'TELEVISOR',
       'COMPUTADORA', 'TELEFONO', 'CELULAR', 'INTERNET', 'SERV_TV_PAGA',
       'SERV_PEL_PAGA', 'CON_VJUEGOS', 'TENENCIA', 'ESCRITURAS', 'FORMA_ADQUI',
       'FINANCIAMIENTO1', 'FINANCIAMIENTO2', 'FINANCIAMIENTO3', 'DEUDA',
       'NUMPERS', 'DUE1_NUM', 'DUE2_NUM', 'MCONMIG', 'MNUMPERS',
       'INGR_PEROTROPAIS', 'INGR_PERDENTPAIS', 'INGR_AYUGOB', 'INGR_JUBPEN',
       'ALIMENTACION', 'ALIM_ADL1', 'ALIM_ADL2', 'ING_ALIM_ADL1',
       'ING_ALIM_ADL2', 'ING_ALIM_ADL3', 'TIPOHOG', 'INGTRHOG', 'JEFE_SEXO',
       'JEFE_EDAD', 'TAMLOC'],
      dtype='object')

In [10]:
poblacion.columns

Index(['ENT', 'MUN', 'LOC50K', 'ID_VIV', 'ID_PERSONA', 'COBERTURA', 'ESTRATO',
       'UPM', 'FACTOR', 'CLAVIVP', 'NUMPER', 'SEXO', 'EDAD', 'PARENTESCO',
       'IDENT_MADRE', 'IDENT_PADRE', 'ENT_PAIS_NAC', 'NACIONALIDAD',
       'SERSALUD', 'AFRODES', 'REGIS_NAC', 'DHSERSAL1', 'DHSERSAL2',
       'RELIGION', 'DIS_VER', 'DIS_OIR', 'DIS_CAMINAR', 'DIS_RECORDAR',
       'DIS_BANARSE', 'DIS_HABLAR', 'DIS_MENTAL', 'CAU_VER', 'CAU_OIR',
       'CAU_CAMINAR', 'CAU_RECORDAR', 'CAU_BANARSE', 'CAU_HABLAR',
       'CAU_MENTAL', 'HLENGUA', 'QDIALECT_INALI', 'HESPANOL', 'ELENGUA',
       'PERTE_INDIGENA', 'ASISTEN', 'MUN_ASI', 'ENT_PAIS_ASI',
       'TIE_TRASLADO_ESCU', 'MED_TRASLADO_ESC1', 'MED_TRASLADO_ESC2',
       'MED_TRASLADO_ESC3', 'NIVACAD', 'ESCOLARI', 'NOMCAR_C', 'ALFABET',
       'ESCOACUM', 'ENT_PAIS_RES_5A', 'MUN_RES_5A', 'CAUSA_MIG_V',
       'SITUA_CONYUGAL', 'IDENT_PAREJA', 'CONACT', 'OCUPACION_C', 'SITTRA',
       'AGUINALDO', 'VACACIONES', 'SERVICIO_MEDICO', 'UTILIDADES',
       'INCAP_SUELDO', 'SAR_AFORE', 'CREDITO_VIVIENDA', 'INGTRMEN', 'HORTRA',
       'ACTIVIDADES_C', 'MUN_TRAB', 'ENT_PAIS_TRAB', 'TIE_TRASLADO_TRAB',
       'MED_TRASLADO_TRAB1', 'MED_TRASLADO_TRAB2', 'MED_TRASLADO_TRAB3',
       'HIJOS_NAC_VIVOS', 'HIJOS_FALLECIDOS', 'HIJOS_SOBREVIV', 'FECHA_NAC_M',
       'FECHA_NAC_A', 'SOBREVIVENCIA', 'IDENT_HIJO', 'EDAD_MORIR_D',
       'EDAD_MORIR_M', 'EDAD_MORIR_A', 'EDAD_MORIR_TD', 'TAMLOC'],
      dtype='object')

In [11]:
solo_en_poblacion = list(set(poblacion.columns) - set(vivienda.columns))
solo_en_vivienda = list(set(vivienda.columns) - set(poblacion.columns))

print("Elementos solo en poblacion:", len(solo_en_poblacion))
print("Elementos solo en vivienda:", len(solo_en_vivienda))
print("Elementos en poblacion en total:", len(poblacion.columns))
print("Elementos en vivienda en total:", len(vivienda.columns))

Elementos solo en poblacion: 81
Elementos solo en vivienda: 73
Elementos en poblacion en total: 91
Elementos en vivienda en total: 83

In [12]:
solo_en_poblacion

['IDENT_PADRE',
 'DIS_BANARSE',
 'ESCOACUM',
 'NIVACAD',
 'MED_TRASLADO_ESC2',
 'IDENT_PAREJA',
 'CAU_OIR',
 'ESCOLARI',
 'EDAD',
 'ENT_PAIS_RES_5A',
 'CONACT',
 'RELIGION',
 'SITUA_CONYUGAL',
 'DIS_MENTAL',
 'SAR_AFORE',
 'INCAP_SUELDO',
 'UTILIDADES',
 'CREDITO_VIVIENDA',
 'ASISTEN',
 'OCUPACION_C',
 'SITTRA',
 'CAU_CAMINAR',
 'MED_TRASLADO_TRAB3',
 'PARENTESCO',
 'VACACIONES',
 'SERSALUD',
 'NOMCAR_C',
 'FECHA_NAC_M',
 'CAU_BANARSE',
 'PERTE_INDIGENA',
 'REGIS_NAC',
 'DIS_CAMINAR',
 'CAU_VER',
 'ALFABET',
 'DIS_VER',
 'ID_PERSONA',
 'ELENGUA',
 'MED_TRASLADO_ESC3',
 'EDAD_MORIR_A',
 'INGTRMEN',
 'EDAD_MORIR_TD',
 'IDENT_MADRE',
 'FECHA_NAC_A',
 'MED_TRASLADO_TRAB1',
 'TIE_TRASLADO_TRAB',
 'CAU_RECORDAR',
 'HESPANOL',
 'IDENT_HIJO',
 'MUN_RES_5A',
 'CAUSA_MIG_V',
 'MED_TRASLADO_TRAB2',
 'AGUINALDO',
 'NUMPER',
 'DIS_RECORDAR',
 'EDAD_MORIR_M',
 'ENT_PAIS_ASI',
 'MED_TRASLADO_ESC1',
 'ENT_PAIS_NAC',
 'NACIONALIDAD',
 'DHSERSAL1',
 'AFRODES',
 'HORTRA',
 'HIJOS_NAC_VIVOS',
 'HIJOS_FALLECIDOS',
 'SEXO',
 'TIE_TRASLADO_ESCU',
 'CAU_MENTAL',
 'HLENGUA',
 'DIS_HABLAR',
 'EDAD_MORIR_D',
 'DIS_OIR',
 'MUN_TRAB',
 'HIJOS_SOBREVIV',
 'DHSERSAL2',
 'CAU_HABLAR',
 'MUN_ASI',
 'QDIALECT_INALI',
 'SERVICIO_MEDICO',
 'ENT_PAIS_TRAB',
 'ACTIVIDADES_C',
 'SOBREVIVENCIA']

In [13]:
cosas = ['PAREDES', 'TECHOS', 'PISOS']
for cosa in cosas: 
    print(f" de {cosa} hay {vivienda[cosa].nunique(dropna=True)}")

 de PAREDES hay 8
 de TECHOS hay 9
 de PISOS hay 3

In [14]:
vivienda

,ENT,MUN,LOC50K,ID_VIV,COBERTURA,ESTRATO,UPM,FACTOR,CLAVIVP,PAREDES,...,ALIM_ADL1,ALIM_ADL2,ING_ALIM_ADL1,ING_ALIM_ADL2,ING_ALIM_ADL3,TIPOHOG,INGTRHOG,JEFE_SEXO,JEFE_EDAD,TAMLOC
0,4,2,1,40020000001,2,04-002-0001-00,1,17,2,8.0,...,2,4,2,4,6,1,NaN,1,73,5
1,4,2,1,40020000002,2,04-002-0001-00,1,17,2,8.0,...,2,4,2,4,6,2,19160.0,1,40,5
2,4,2,1,40020000003,2,04-002-0001-00,1,17,2,8.0,...,2,4,2,4,6,1,34400.0,1,45,5
3,4,2,1,40020000004,2,04-002-0001-00,1,17,1,8.0,...,2,4,2,4,6,5,NaN,3,70,5
4,4,2,1,40020000005,2,04-002-0001-00,1,17,1,8.0,...,2,4,2,4,6,1,5160.0,1,45,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4792,4,2,0,40020004793,2,04-002-0000-03,41,21,1,8.0,...,2,4,2,4,6,1,5000.0,1,20,1
4793,4,2,0,40020004794,2,04-002-0000-03,41,21,1,8.0,...,2,4,2,4,6,1,4167.0,1,45,1
4794,4,2,0,40020004795,2,04-002-0000-03,42,20,1,8.0,...,2,4,2,4,6,5,33333.0,1,58,1
4795,4,2,0,40020004796,2,04-002-0000-03,43,21,1,8.0,...,2,4,2,4,6,1,0.0,1,55,1
4796,4,2,0,40020004797,2,04-002-0000-03,43,21,1,8.0,...,2,4,2,4,6,1,10750.0,1,31,1

In [15]:
print(f"En {nombre_mun} hay {vivienda['FACTOR'].sum():,} viviendas")

En San Francisco de Campeche hay 84,524 viviendas

In [16]:
vivienda['MUN'].nunique(dropna=True)

1

In [17]:
suma_factor_por_mun = vivienda.groupby('MUN', as_index=False)['FACTOR'].sum()
suma_factor_por_mun.rename(columns={'FACTOR': 'suma_factor'}, inplace=True)
suma_factor_por_mun

   MUN  suma_factor
0    2        84524

In [18]:
suma_factor_por_mun['suma_factor'].min()

np.int64(84524)

In [19]:
f = '../data/Personas00.CSV'
per = pd.read_csv(f,  nrows=5
                       # usecols = ['folioviv','aire_acond','entidad','factor']
                      )
per

,ENT,MUN,LOC50K,ID_VIV,ID_PERSONA,COBERTURA,ESTRATO,UPM,FACTOR,CLAVIVP,...,HIJOS_SOBREVIV,FECHA_NAC_M,FECHA_NAC_A,SOBREVIVENCIA,IDENT_HIJO,EDAD_MORIR_D,EDAD_MORIR_M,EDAD_MORIR_A,EDAD_MORIR_TD,TAMLOC
0,1,1,1,10010000001,1001000000100001,2,01-001-0001-00,1,59,1,...,2.0,9.0,2001.0,1.0,3.0,NaN,NaN,NaN,NaN,5
1,1,1,1,10010000001,1001000000100002,2,01-001-0001-00,1,59,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
2,1,1,1,10010000001,1001000000100003,2,01-001-0001-00,1,59,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,1,1,1,10010000002,1001000000200001,2,01-001-0001-00,1,59,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
4,1,1,1,10010000002,1001000000200002,2,01-001-0001-00,1,59,1,...,2.0,5.0,2009.0,1.0,4.0,NaN,NaN,NaN,NaN,5

In [20]:
per.columns

Index(['ENT', 'MUN', 'LOC50K', 'ID_VIV', 'ID_PERSONA', 'COBERTURA', 'ESTRATO',
       'UPM', 'FACTOR', 'CLAVIVP', 'NUMPER', 'SEXO', 'EDAD', 'PARENTESCO',
       'IDENT_MADRE', 'IDENT_PADRE', 'ENT_PAIS_NAC', 'NACIONALIDAD',
       'SERSALUD', 'AFRODES', 'REGIS_NAC', 'DHSERSAL1', 'DHSERSAL2',
       'RELIGION', 'DIS_VER', 'DIS_OIR', 'DIS_CAMINAR', 'DIS_RECORDAR',
       'DIS_BANARSE', 'DIS_HABLAR', 'DIS_MENTAL', 'CAU_VER', 'CAU_OIR',
       'CAU_CAMINAR', 'CAU_RECORDAR', 'CAU_BANARSE', 'CAU_HABLAR',
       'CAU_MENTAL', 'HLENGUA', 'QDIALECT_INALI', 'HESPANOL', 'ELENGUA',
       'PERTE_INDIGENA', 'ASISTEN', 'MUN_ASI', 'ENT_PAIS_ASI',
       'TIE_TRASLADO_ESCU', 'MED_TRASLADO_ESC1', 'MED_TRASLADO_ESC2',
       'MED_TRASLADO_ESC3', 'NIVACAD', 'ESCOLARI', 'NOMCAR_C', 'ALFABET',
       'ESCOACUM', 'ENT_PAIS_RES_5A', 'MUN_RES_5A', 'CAUSA_MIG_V',
       'SITUA_CONYUGAL', 'IDENT_PAREJA', 'CONACT', 'OCUPACION_C', 'SITTRA',
       'AGUINALDO', 'VACACIONES', 'SERVICIO_MEDICO', 'UTILIDADES',
       'INCAP_SUELDO', 'SAR_AFORE', 'CREDITO_VIVIENDA', 'INGTRMEN', 'HORTRA',
       'ACTIVIDADES_C', 'MUN_TRAB', 'ENT_PAIS_TRAB', 'TIE_TRASLADO_TRAB',
       'MED_TRASLADO_TRAB1', 'MED_TRASLADO_TRAB2', 'MED_TRASLADO_TRAB3',
       'HIJOS_NAC_VIVOS', 'HIJOS_FALLECIDOS', 'HIJOS_SOBREVIV', 'FECHA_NAC_M',
       'FECHA_NAC_A', 'SOBREVIVENCIA', 'IDENT_HIJO', 'EDAD_MORIR_D',
       'EDAD_MORIR_M', 'EDAD_MORIR_A', 'EDAD_MORIR_TD', 'TAMLOC'],
      dtype='object')

### Variables de la tabla poblacion que no se consideran de momento: 
- IDENT_MADRE: ¿La madre de (NOMBRE) vive en esta vivienda?   ¿Quién es?
- IDENT_PADRE: ¿El padre de (NOMBRE) vive en esta vivienda?   ¿Quién es?
- ENT_PAIS_NA: ¿En qué estado de la República Mexicana o en qué país nació (NOMBRE)?
- NACIONALIDA: ¿(NOMBRE) tiene nacionalidad mexicana?
- SERSALUD: Cuando (NOMBRE) tiene problemas de salud, ¿en dónde se atiende?
- AFRODES: Por sus antepasados y de acuerdo con sus costumbres y tradiciones, ¿(NOMBRE) se considera afromexicano(a) negro(a) o afrodescendiente?
- REGIS_NAC: ¿(NOMBRE) tiene acta de nacimiento o está inscrita(o) en el registro civil de:
- DHSERSAL1, DHSERSAL2: ¿(NOMBRE) está afiliada(o) o tiene derecho a servicios médicos en:
- RELIGION	¿Cuál es la religión de (NOMBRE)?